version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # dem:
  #   build: .
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/dem
  #   ports:
  #     - "5001:5001"
  #   volumes:
  #     - ./extractions:/app/extractions
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data: 